apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
      app: darius
    name: deployment-darius-a100-latest
    namespace: darius
spec:
    replicas: 1
    selector:
      matchLabels:
        app: darius
    strategy:
      type: Recreate
    template:
      metadata:
        # creationTimestamp: null
        labels:
          app: darius
      spec:
        # affinity:
        #   podAntiAffinity:
        #     requiredDuringSchedulingIgnoredDuringExecution:
        #     - labelSelector:
        #         matchExpressions:
        #         - key: app
        #           operator: In
        #           values:
        #           - darius
        #       topologyKey: kubernetes.io/hostname
        volumes:
        - name: volume-darius
          persistentVolumeClaim:
            claimName: pvc-darius
        - name: nfs-bonn-epyc
          nfs:
            path: /data/
            server: bonn-epyc
        - name: nfs-bonn-pe940
          nfs:
            path: /data/
            server: bonn-pe940
        - name: apt-config
          configMap:
            name: apt-config
        # - name: volume-imsb
        #   persistentVolumeClaim:
        #     claimName: pvc-imsb-bonn-dgx-a100
        containers:
        - securityContext:
            # allowPrivilegeEscalation: false
            # capabilities:
            #   drop:
            #   - ALL
            runAsNonRoot: true
            runAsUser: 2856
          command:
          - sleep
          - infinity
          image: human0815/cuda-conda:12.2.2-cudnn8-runtime-ubuntu20.04-updated
          imagePullPolicy: Always
          name: darius
          envFrom:
          - configMapRef:
              name: proxy-config
          resources:
            limits:
              memory: 128Gi
              nvidia.com/gpu: "1"
            requests:
              cpu: "8"
              memory: 128Gi
              nvidia.com/gpu: "1"
          volumeMounts:
          - mountPath: /data/
            name: volume-darius
          - mountPath: /poweredge/
            name: nfs-bonn-pe940
          - mountPath: /epyc/
            name: nfs-bonn-epyc
          - mountPath: /etc/apt/apt.conf
            name: apt-config
            subPath: apt.conf
          # - mountPath: /
          #   name: volume-imsb
        dnsPolicy: ClusterFirst
        enableServiceLinks: true
        preemptionPolicy: PreemptLowerPriority
        priority: 0
        nodeSelector:
          kubernetes.io/hostname: bonn-dgx-a100
          # kubernetes.io/hostname: deltabonn-2
          # kubernetes.io/hostname: deltabonn-h100
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30        