apiVersion: apps/v1
kind: StatefulSet
metadata:
    labels:
      app: darius
    name: statefulset-darius
    namespace: imsb
spec:
    serviceName: darius
    replicas: 1
    selector:
      matchLabels:
        app: darius
    template:
      metadata:
        labels:
          app: darius
      spec:
        volumes:
        - name: volume-poweredge
          persistentVolumeClaim:
            claimName: pvc-imsb-bonn-pe940
        - name: volume-deltabonn-6
          persistentVolumeClaim:
            claimName: pvc-deltabonn-6
        - name: volume-epyc
          persistentVolumeClaim:
            claimName: pvc-imsb-bonn-epyc
        containers:
        - securityContext: {}
          command:
          - sleep
          - infinity
          image: human0815/cuda-conda:12.8.1-v5
          imagePullPolicy: Always
          name: darius
          resources:
            limits:
              memory: 256Gi
              nvidia.com/gpu: "1"
            requests:
              cpu: "8"
              memory: 256Gi
              nvidia.com/gpu: "1"
          volumeMounts:
          - mountPath: /poweredge
            name: volume-poweredge
            subPath: .
          - mountPath: /deltabonn-6
            name: volume-deltabonn-6
            subPath: .
          - mountPath: /epyc/projects/dschaub
            name: volume-deltabonn-6
            subPath: dschaub
          - mountPath: /bonn-epyc
            name: volume-epyc
        dnsPolicy: ClusterFirst
        enableServiceLinks: true
        preemptionPolicy: PreemptLowerPriority
        priority: 0
        nodeSelector:
          nvidia.com/gpu.product: NVIDIA-A100-SXM4-40GB
          # nvidia.com/gpu.product: NVIDIA-H100-PCIe

        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30         